# This is a basic workflow to help you get started with Actions

name: Manual Build

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version:
        description: Build version
        type: string
        default: test
        required: true
      output:
        description: Appliance output type
        type: choice
        options:
          - all 
          - virtualbox-iso 
          - vmware-iso 
          - qemu

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ["self-hosted"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Manual Build All
        if: github.event.inputs.output == "all"
        run: ./packer_build.sh -u -v ${{ github.event.inputs.version }}

      - name: Manual Build ${{ inputs.output }}
        if: github.event.inputs.output != "all"
        run: ./packer_build.sh -u -v ${{ github.event.inputs.version }} -o ${{ github.event.inputs.output }}
