# This is a basic workflow to help you get started with Actions

name: Packer Build

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ["self-hosted"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: MEGA Login
        run: mega-login ${{ secrets.mega_email }} ${{ secrets.mega_password }}

      # Runs a set of commands using the runners shell
      - name: MEGA ls
        run: mega-ls
